import type { Ticket } from "./types"

export function getMockTickets(): Ticket[] {
  return [
    {
      id: "EVT-001",
      title: "HCR 1st Reactor Inlet Temperature 상승 이상",
      description: "HCR 1st Reactor Inlet Temperature가 Guide 상한(400C)을 초과하여 412C까지 상승. 촉매 비활성화 및 코킹 가능성 검토 필요.",
      ticketType: "Trouble",
      priority: "P1",
      impact: "Safety",
      owner: "김지수",
      requester: "박성호",
      status: "In Progress",
      createdDate: "2025-02-01",
      dueDate: "2025-02-08",
      accessLevel: "Team",
      allowedTeams: ["공정기술팀", "생산조정팀"],
      unit: "HCR",
      area: "Reaction",
      equipment: "1st Reactor (R-301)",
      tags: ["TI-2001", "TI-2002", "PI-3001"],
      fromTime: "2025-02-01T06:00",
      toTime: "2025-02-01T14:00",
      context: {
        unit: "HCR",
        area: "Reaction",
        equipment: "1st Reactor (R-301)",
        tags: ["TI-2001", "TI-2002", "PI-3001"],
        timeRange: "2025-02-01 06:00 ~ 14:00",
      },
      processStatus: "review",
      processFlow: [
        { step: "issued", label: "이벤트 발행", status: "completed", assignee: "박성호", team: "생산조정팀", timestamp: "2025-02-01 14:30" },
        { step: "accepted", label: "접수", status: "completed", assignee: "김지수", team: "공정기술팀", timestamp: "2025-02-01 15:00" },
        { step: "review", label: "기술검토", status: "current", assignee: "김지수", team: "공정기술팀" },
        { step: "publisher-confirm", label: "발행자 확인", status: "upcoming" },
        { step: "closed", label: "종결", status: "upcoming" },
      ],
      workPackages: [],
      messages: [
        { id: "msg-001", ticketId: "EVT-001", author: "박성호", role: "requester", messageType: "opinion", content: "운전 중 TI-2001 알람 발생하여 긴급 이벤트 생성합니다. 현재 온도 412C로 Guide 상한 초과 상태입니다.", timestamp: "2025-02-01T14:30:00Z" },
        { id: "msg-002", ticketId: "EVT-001", author: "System", role: "system", messageType: "status_change", content: "김지수님이 이벤트를 접수하였습니다.", timestamp: "2025-02-01T15:00:00Z" },
      ],
      opinions: [
        {
          id: "op-001", author: "김지수", team: "공정기술팀",
          templateType: "troubleshooting", templateLabel: "트러블슈팅",
          fields: [
            { label: "현상 분석", value: "TI-2001 기준 412C 도달. Guide 상한 400C 초과. 과거 유사 사례 대비 상승 속도가 빠름." },
            { label: "추정 원인", value: "1) Feed 조성 변화 (Heavy 비율 증가)\n2) 촉매 활성도 저하 가능성\n3) Quench Gas 유량 부족" },
          ],
          status: "draft", createdAt: "2025-02-01T16:00:00Z",
        },
      ],
      comments: [
        { id: "cmt-001", author: "박성호", content: "현재 Quench 유량 증가시켜 임시 조치 중입니다. 기술검토 부탁드립니다.", timestamp: "2025-02-01T14:35:00Z" },
        { id: "cmt-002", author: "김지수", content: "접수했습니다. Feed 분석 데이터 확인 후 의견 드리겠습니다.", timestamp: "2025-02-01T15:05:00Z" },
      ],
      additionalDetails: {
        text: "이벤트 발생 전후 온도 추이를 확인할 수 있는 트렌드와 DCS 화면을 첨부합니다. 06:00부터 급격한 온도 상승이 관찰됩니다.",
        dataBoxes: [
          {
            id: "db-001",
            type: "trend",
            config: {
              tags: ["TI-2001", "TI-2002", "TI-2003"],
              title: "Reactor Inlet Temperature Trend",
              fromDate: "2025-02-01T06:00",
              toDate: "2025-02-01T14:00",
              unit: "°C",
            },
          },
          {
            id: "db-002",
            type: "dcs",
            config: {
              graphicNumber: "HCR-001",
              graphicType: "Process Overview",
              title: "HCR Reactor Section DCS 화면",
            },
          },
          {
            id: "db-003",
            type: "table",
            config: {
              title: "이벤트 발생 전후 주요 변수 비교",
              rows: 4,
              columns: 4,
              tableData: [
                ["변수", "정상 운전", "이벤트 시", "차이"],
                ["TI-2001 (°C)", "395", "412", "+17"],
                ["PI-3001 (kg/cm²)", "152", "155", "+3"],
                ["FI-4001 (BPD)", "12,500", "12,800", "+300"],
              ],
            },
          },
        ],
      },
    },
    {
      id: "EVT-002",
      title: "VDU Overhead Temperature 가이드 재검토",
      description: "생산조정팀 요청: VDU 컬럼 오버헤드 온도 가이드 재검토. 최근 Feed 변경 이후 기존 가이드 적정성 확인 필요.",
      ticketType: "Improvement",
      priority: "P3",
      impact: "Throughput",
      owner: "김지수",
      requester: "이민석",
      status: "In Progress",
      createdDate: "2025-01-28",
      dueDate: "2025-02-15",
      accessLevel: "Team",
      allowedTeams: ["공정기술팀", "생산조정팀"],
      unit: "VDU",
      area: "Distillation",
      equipment: "VDU Column (T-201)",
      tags: ["TI-4501", "TI-4502"],
      fromTime: "2025-01-25T00:00",
      toTime: "2025-01-28T23:59",
      context: {
        unit: "VDU",
        area: "Distillation",
        equipment: "VDU Column (T-201)",
        tags: ["TI-4501", "TI-4502"],
        timeRange: "2025-01-25 ~ 01-28",
      },
      processStatus: "additional-review",
      processFlow: [
        { step: "issued", label: "이벤트 발행", status: "completed", assignee: "이민석", team: "생산조정팀", timestamp: "2025-01-28 09:00" },
        { step: "accepted", label: "접수", status: "completed", assignee: "김지수", team: "공정기술팀", timestamp: "2025-01-28 10:30" },
        { step: "review", label: "기술검토", status: "completed", assignee: "김지수", team: "공정기술팀", timestamp: "2025-01-29 14:00" },
        { step: "additional-review", label: "추가검토", status: "current", assignee: "최영호", team: "장치기술팀" },
        { step: "publisher-confirm", label: "발행자 확인", status: "upcoming" },
        { step: "closed", label: "종결", status: "upcoming" },
      ],
      additionalReviewers: [
        { id: "rev-001", name: "최영호", team: "장치기술팀", status: "completed", assignedAt: "2025-01-29T14:30:00Z", opinion: "장치 측면 검토 완료. Overhead 온도 상향 조정 시 응력 측면에서 문제 없음. 다만 급격한 온도 변화는 피해주시기 바랍니다.", completedAt: "2025-01-30T10:00:00Z" },
        { id: "rev-002", name: "김기동", team: "장치팀", status: "in-progress", assignedAt: "2025-01-30T11:00:00Z" },
        { id: "rev-003", name: "이승환", team: "에너지관리팀", status: "pending", assignedAt: "2025-01-30T11:00:00Z" },
      ],
      workPackages: [],
      messages: [
        { id: "msg-010", ticketId: "EVT-002", author: "이민석", role: "requester", messageType: "opinion", content: "W600N 모드 전환 후 VDU Overhead 온도가 기존 가이드에서 자주 벗어나고 있습니다.", timestamp: "2025-01-28T09:00:00Z" },
        { id: "msg-011", ticketId: "EVT-002", author: "System", role: "system", messageType: "status_change", content: "김지수님이 이벤트를 접수하였습니다.", timestamp: "2025-01-28T10:30:00Z" },
        { id: "msg-012", ticketId: "EVT-002", author: "김지수", role: "assignee", messageType: "opinion", content: "1차 검토 완료. VDU 열수지 분석 결과 Overhead 온도 가이드를 122~128C로 조정하는 것이 적절합니다. 장치 측면 검토를 위해 장치기술팀에 추가 검토 요청합니다.", timestamp: "2025-01-29T14:00:00Z" },
        { id: "msg-013", ticketId: "EVT-002", author: "System", role: "system", messageType: "wp_assignment", content: "최영호님(장치기술팀)에게 추가 검토가 요청되었습니다.", timestamp: "2025-01-29T14:30:00Z" },
      ],
      opinions: [
        {
          id: "op-010", author: "김지수", team: "공정기술팀",
          templateType: "improvement", templateLabel: "개선아이템",
          fields: [
            { key: "status", label: "현상", value: "VDU Overhead Temp 기존 가이드(118~124C) 대비 2~4C 상승 운전 중" },
            { key: "analysis", label: "분석 결과", value: "Feed 변경(W600N) 이후 컬럼 열수지 변화. 시뮬레이션 결과 122~128C가 적정." },
            { key: "proposal", label: "개선 제안", value: "Operation Guide 상 Overhead Temp 가이드를 122~128C로 조정 권고" },
          ],
          status: "submitted", createdAt: "2025-01-29T13:00:00Z", submittedAt: "2025-01-29T14:00:00Z",
        },
        {
          id: "op-011", author: "최영호", team: "장치기술팀",
          templateType: "additional-review", templateLabel: "추가검토 의견",
          fields: [
            { key: "analysis", label: "검토 분석", value: "장치 측면 검토 완료. Overhead 온도 상향 조정 시 응력 측면에서 문제 없음. 다만 급격한 온도 변화는 피해주시기 바랍니다." },
          ],
          status: "submitted", createdAt: "2025-01-30T09:00:00Z", submittedAt: "2025-01-30T10:00:00Z",
        },
      ],
      comments: [
        { id: "cmt-010", author: "이민석", content: "검토 감사합니다. 장치 측면에서 문제없다면 바로 적용 가능합니다.", timestamp: "2025-01-29T14:20:00Z" },
      ],
    },
    {
      id: "EVT-003",
      title: "CDU Furnace 효율 저하 분석",
      description: "CDU Furnace Coil Outlet Temperature 기준 열효율이 설계 대비 5% 이상 저하. 에너지 효율 개선 방안 검토 요청.",
      ticketType: "Analysis",
      priority: "P2",
      impact: "Energy",
      owner: "김지수",
      requester: "정태영",
      status: "In Progress",
      createdDate: "2025-01-25",
      dueDate: "2025-02-20",
      accessLevel: "Public",
      unit: "CDU",
      area: "Heating",
      equipment: "CDU Furnace (F-101)",
      tags: ["TI-1001", "FI-1001", "EFF-CDU"],
      fromTime: "2025-01-15T00:00",
      toTime: "2025-01-25T23:59",
      context: {
        unit: "CDU",
        area: "Heating",
        equipment: "CDU Furnace (F-101)",
        tags: ["TI-1001", "FI-1001"],
        timeRange: "2025-01-15 ~ 01-25",
      },
      processStatus: "review",
      processFlow: [
        { step: "issued", label: "이벤트 발행", status: "completed", assignee: "정태영", team: "에너지관리팀", timestamp: "2025-01-25 10:00" },
        { step: "accepted", label: "접수", status: "completed", assignee: "김지수", team: "공정기술팀", timestamp: "2025-01-25 14:00" },
        { step: "review", label: "기술검토", status: "current", assignee: "김지수", team: "공정기술팀" },
        { step: "publisher-confirm", label: "발행자 확인", status: "upcoming" },
        { step: "closed", label: "종결", status: "upcoming" },
      ],
      workPackages: [],
      messages: [
        { id: "msg-020", ticketId: "EVT-003", author: "정태영", role: "requester", messageType: "opinion", content: "CDU Furnace 열효율 모니터링 결과 설계 대비 5.2% 저하 확인. 원인 분석 및 개선 방안 검토 요청드립니다.", timestamp: "2025-01-25T10:00:00Z" },
        { id: "msg-021", ticketId: "EVT-003", author: "System", role: "system", messageType: "status_change", content: "김지수님이 이벤트를 접수하였습니다.", timestamp: "2025-01-25T14:00:00Z" },
      ],
      opinions: [],
      comments: [],
    },
    {
      id: "EVT-004",
      title: "HCR Feed/Effluent 열교환기 Fouling 가속화",
      description: "TI-2931 열교환기 Fouling 모니터링 결과 UA Value 급격 하락. Online Cleaning 또는 운전 조건 변경 검토 필요.",
      ticketType: "Trouble",
      priority: "P2",
      impact: "Throughput",
      owner: "김지수",
      requester: "박성호",
      status: "In Progress",
      createdDate: "2025-02-02",
      dueDate: "2025-02-10",
      accessLevel: "Team",
      allowedTeams: ["공정기술팀", "장치팀", "생산조정팀"],
      unit: "HCR",
      area: "Heat Exchange",
      equipment: "Feed/Effluent HEX (E-301)",
      tags: ["TI-2931", "UA-301"],
      fromTime: "2025-01-28T00:00",
      toTime: "2025-02-02T10:00",
      context: {
        unit: "HCR",
        area: "Heat Exchange",
        equipment: "Feed/Effluent HEX (E-301)",
        tags: ["TI-2931", "UA-301"],
        timeRange: "2025-01-28 ~ 02-02",
      },
      processStatus: "additional-review",
      processFlow: [
        { step: "issued", label: "이벤트 발행", status: "completed", assignee: "박성호", team: "생산조정팀", timestamp: "2025-02-02 10:15" },
        { step: "accepted", label: "접수", status: "completed", assignee: "김지수", team: "공정기술팀", timestamp: "2025-02-02 11:00" },
        { step: "review", label: "기술검토", status: "completed", assignee: "김지수", team: "공정기술팀", timestamp: "2025-02-02 16:00" },
        { step: "additional-review", label: "추가검토", status: "current", assignee: "한정민", team: "장치팀" },
        { step: "publisher-confirm", label: "발행자 확인", status: "upcoming" },
        { step: "closed", label: "종결", status: "upcoming" },
      ],
      additionalReviewer: { name: "한정민", team: "장치팀", status: "in-progress", assignedAt: "2025-02-02T16:30:00Z" },
      workPackages: [],
      messages: [
        { id: "msg-030", ticketId: "EVT-004", author: "박성호", role: "requester", messageType: "opinion", content: "E-301 UA Value가 2주 전 대비 15% 하락. Fouling 가속화로 판단됩니다.", timestamp: "2025-02-02T10:15:00Z" },
        { id: "msg-031", ticketId: "EVT-004", author: "System", role: "system", messageType: "status_change", content: "김지수님이 이벤트를 접수하였습니다.", timestamp: "2025-02-02T11:00:00Z" },
        { id: "msg-032", ticketId: "EVT-004", author: "김지수", role: "assignee", messageType: "opinion", content: "공정 측면 검토 완료. Fouling Rate 가속 확인. 장치팀에 Cleaning 일정 검토 요청합니다.", timestamp: "2025-02-02T16:00:00Z" },
        { id: "msg-033", ticketId: "EVT-004", author: "System", role: "system", messageType: "wp_assignment", content: "한정민님(장치팀)에게 추가 검토가 요청되었습니다.", timestamp: "2025-02-02T16:30:00Z" },
      ],
      opinions: [
        {
          id: "op-030", author: "김지수", team: "공정기술팀",
          templateType: "troubleshooting", templateLabel: "트러블슈팅",
          fields: [
            { label: "현상 분석", value: "E-301 UA Value 급격 하락 (480 → 410 W/m2K). 전주 대비 Fouling Rate 2배 가속." },
            { label: "추정 원인", value: "W600N 모드 전환 후 Heavy Feed 비율 증가로 인한 코크 형성 가속" },
            { label: "조치 권고", value: "1주 내 Online Chemical Cleaning 권고. 장치 팀 일정 확인 필요." },
          ],
          status: "submitted", createdAt: "2025-02-02T15:00:00Z", submittedAt: "2025-02-02T16:00:00Z",
        },
      ],
      comments: [],
    },
    {
      id: "EVT-005",
      title: "CCR Catalyst Activity 모니터링 이상",
      description: "CCR Reactor Catalyst Activity Index가 정상 범위 하한에 근접. 촉매 재생 사이클 조정 필요성 검토 요청.",
      ticketType: "Analysis",
      priority: "P2",
      impact: "Quality",
      owner: "김지수",
      requester: "윤서연",
      status: "Open",
      createdDate: "2025-02-02",
      dueDate: "2025-02-12",
      accessLevel: "Team",
      allowedTeams: ["공정기술팀", "촉매기술팀"],
      unit: "CCR",
      area: "Reaction",
      equipment: "CCR Reactor (R-401)",
      tags: ["AI-4001", "CAT-401"],
      fromTime: "2025-01-20T00:00",
      toTime: "2025-02-02T00:00",
      context: {
        unit: "CCR",
        area: "Reaction",
        equipment: "CCR Reactor (R-401)",
        tags: ["AI-4001", "CAT-401"],
        timeRange: "2025-01-20 ~ 02-02",
      },
      processStatus: "issued",
      processFlow: [
        { step: "issued", label: "이벤트 발행", status: "current", assignee: "윤서연", team: "촉매기술팀", timestamp: "2025-02-02 11:00" },
        { step: "accepted", label: "접수", status: "upcoming", assignee: "김지수", team: "공정기술팀" },
        { step: "review", label: "기술검토", status: "upcoming" },
        { step: "publisher-confirm", label: "발행자 확인", status: "upcoming" },
        { step: "closed", label: "종결", status: "upcoming" },
      ],
      workPackages: [],
      messages: [
        { id: "msg-040", ticketId: "EVT-005", author: "윤서연", role: "requester", messageType: "opinion", content: "CCR Catalyst Activity Index 0.72로 하한(0.70) 근접. 재생 주기 검토 필요합니다.", timestamp: "2025-02-02T11:00:00Z" },
      ],
      opinions: [],
      comments: [],
    },
    {
      id: "EVT-006",
      title: "NHT Stripper 압력 이상 발생",
      description: "NHT Stripper Column 압력이 정상 범위를 초과. 안전 밸브 동작 전 조치 필요.",
      ticketType: "Trouble",
      priority: "P1",
      impact: "Safety",
      owner: "김지수",
      requester: "박성호",
      status: "Open",
      createdDate: "2025-02-02",
      dueDate: "2025-02-03",
      accessLevel: "Team",
      allowedTeams: ["공정기술팀", "생산조정팀", "안전환경팀"],
      unit: "NHT",
      area: "Stripping",
      equipment: "Stripper Column (T-501)",
      tags: ["PI-5001", "PSV-501"],
      fromTime: "2025-02-02T08:00",
      toTime: "2025-02-02T12:00",
      context: {
        unit: "NHT",
        area: "Stripping",
        equipment: "Stripper Column (T-501)",
        tags: ["PI-5001", "PSV-501"],
        timeRange: "2025-02-02 08:00 ~ 12:00",
      },
      processStatus: "issued",
      processFlow: [
        { step: "issued", label: "이벤트 발행", status: "current", assignee: "박성호", team: "생산조정팀", timestamp: "2025-02-02 12:30" },
        { step: "accepted", label: "접수", status: "upcoming", assignee: "김지수", team: "공정기술팀" },
        { step: "review", label: "기술검토", status: "upcoming" },
        { step: "publisher-confirm", label: "발행자 확인", status: "upcoming" },
        { step: "closed", label: "종결", status: "upcoming" },
      ],
      workPackages: [],
      messages: [
        { id: "msg-050", ticketId: "EVT-006", author: "박성호", role: "requester", messageType: "opinion", content: "NHT Stripper 압력 12.5 kg/cm2 (정상 10.0). 긴급 검토 요청합니다.", timestamp: "2025-02-02T12:30:00Z" },
      ],
      opinions: [],
      comments: [],
    },
    {
      id: "EVT-007",
      title: "VDU HVGO Draw Temperature 최적화",
      description: "VDU HVGO Draw Temperature 조정을 통한 수율 개선 방안 검토. 현재 운전 조건 대비 HVGO 수율 2% 향상 가능성 분석.",
      ticketType: "Improvement",
      priority: "P3",
      impact: "Yield",
      owner: "김지수",
      requester: "김지수",
      status: "In Progress",
      createdDate: "2025-01-20",
      dueDate: "2025-02-28",
      accessLevel: "Team",
      allowedTeams: ["공정기술팀"],
      unit: "VDU",
      area: "Distillation",
      equipment: "VDU Column (T-201)",
      tags: ["TI-4510", "FI-4502"],
      fromTime: "2025-01-10T00:00",
      toTime: "2025-01-20T23:59",
      context: {
        unit: "VDU",
        area: "Distillation",
        equipment: "VDU Column (T-201)",
        tags: ["TI-4510", "FI-4502"],
        timeRange: "2025-01-10 ~ 01-20",
      },
      processStatus: "review",
      processFlow: [
        { step: "issued", label: "이벤트 발행", status: "completed", assignee: "김지수", team: "공정기술팀", timestamp: "2025-01-20 09:00" },
        { step: "accepted", label: "접수", status: "completed", assignee: "김지수", team: "공정기술팀", timestamp: "2025-01-20 09:00" },
        { step: "review", label: "기술검토", status: "current", assignee: "김지수", team: "공정기술팀" },
        { step: "publisher-confirm", label: "발행자 확인", status: "upcoming" },
        { step: "closed", label: "종결", status: "upcoming" },
      ],
      workPackages: [],
      messages: [],
      opinions: [],
      comments: [],
    },
    {
      id: "EVT-008",
      title: "CDU Desalter 효율 저하 원인 분석",
      description: "CDU Desalter 탈염 효율이 95% 미만으로 하락. Crude Oil 내 Salt Content 증가로 인한 하류 부식 위험성 검토 필요.",
      ticketType: "Trouble",
      priority: "P2",
      impact: "Quality",
      owner: "김지수",
      requester: "정태영",
      status: "In Progress",
      createdDate: "2025-01-30",
      dueDate: "2025-02-15",
      accessLevel: "Team",
      allowedTeams: ["공정기술팀", "에너지관리팀", "장치기술팀"],
      unit: "CDU",
      area: "Desalting",
      equipment: "Desalter (V-101)",
      tags: ["AI-1001", "FI-1010"],
      fromTime: "2025-01-28T00:00",
      toTime: "2025-01-30T23:59",
      context: {
        unit: "CDU",
        area: "Desalting",
        equipment: "Desalter (V-101)",
        tags: ["AI-1001", "FI-1010"],
        timeRange: "2025-01-28 ~ 01-30",
      },
      processStatus: "publisher-confirm",
      processFlow: [
        { step: "issued", label: "이벤트 발행", status: "completed", assignee: "정태영", team: "에너지관리팀", timestamp: "2025-01-30 09:00" },
        { step: "accepted", label: "접수", status: "completed", assignee: "김지수", team: "공정기술팀", timestamp: "2025-01-30 10:00" },
        { step: "review", label: "기술검토", status: "completed", assignee: "김지수", team: "공정기술팀", timestamp: "2025-01-31 16:00" },
        { step: "publisher-confirm", label: "발행자 확인", status: "current", assignee: "정태영", team: "에너지관리팀", timestamp: "2025-02-01 10:00" },
        { step: "closed", label: "종결", status: "upcoming" },
      ],
      workPackages: [],
      messages: [
        { id: "msg-060", ticketId: "EVT-008", author: "정태영", role: "requester", messageType: "opinion", content: "Desalter 탈염 효율 92% 확인. 하류 부식 위험 점검 필요합니다.", timestamp: "2025-01-30T09:00:00Z" },
        { id: "msg-061", ticketId: "EVT-008", author: "System", role: "system", messageType: "status_change", content: "김지수님이 이벤트를 접수하였습니다.", timestamp: "2025-01-30T10:00:00Z" },
        { id: "msg-062", ticketId: "EVT-008", author: "김지수", role: "assignee", messageType: "opinion", content: "분석 완료. Wash Water 유량 증가 및 Demulsifier 주입량 조정으로 효율 97%로 회복 확인.", timestamp: "2025-01-31T16:00:00Z" },
        { id: "msg-063", ticketId: "EVT-008", author: "System", role: "system", messageType: "status_change", content: "기술검토가 완료되었습니다. 정태영님(이벤트 발행자)의 최종 확인 대기 중.", timestamp: "2025-02-01T10:00:00Z" },
      ],
      opinions: [
        {
          id: "op-060", author: "김지수", team: "공정기술팀",
          templateType: "analysis-review", templateLabel: "분석 검토",
          fields: [
            { label: "분석 항목", value: "CDU Desalter 탈염 효율 저하 원인" },
            { label: "분석 결과", value: "Crude 변경(Arab Extra Light → Arab Light) 이후 에멀전 안정도 증가. Wash Water Ratio 부족(현 5.0% → 권고 6.5%)." },
            { label: "조치 사항", value: "Wash Water 유량 6.5%로 증가, Demulsifier A 10ppm 추가 주입" },
            { label: "효과 확인", value: "조치 후 48시간 모니터링 결과 탈염 효율 97.2%로 회복 확인" },
          ],
          status: "submitted", createdAt: "2025-01-31T14:00:00Z", submittedAt: "2025-01-31T16:00:00Z",
        },
      ],
      comments: [
        { id: "cmt-060", author: "정태영", content: "빠른 조치 감사합니다. 종결 처리 부탁드립니다.", timestamp: "2025-02-01T11:00:00Z" },
      ],
    },
    {
      id: "EVT-009",
      title: "FCC Riser Outlet Temperature 변동성 증가",
      description: "FCC Riser Outlet Temperature 변동폭이 증가하여 Product Quality 영향 가능성 검토.",
      ticketType: "Analysis",
      priority: "P3",
      impact: "Quality",
      owner: "김지수",
      requester: "강민우",
      status: "In Progress",
      createdDate: "2025-01-27",
      dueDate: "2025-02-10",
      accessLevel: "Team",
      allowedTeams: ["공정기술팀"],
      unit: "FCC",
      area: "Reaction",
      equipment: "FCC Riser",
      tags: ["TI-6001", "TI-6002"],
      fromTime: "2025-01-20T00:00",
      toTime: "2025-01-27T23:59",
      context: {
        unit: "FCC",
        area: "Reaction",
        equipment: "FCC Riser",
        tags: ["TI-6001", "TI-6002"],
        timeRange: "2025-01-20 ~ 01-27",
      },
      processStatus: "verbal-closed",
      processFlow: [
        { step: "issued", label: "이벤트 발행", status: "completed", assignee: "강민우", team: "생산조정팀", timestamp: "2025-01-27 14:00" },
        { step: "verbal-closed", label: "구두 설명 후 종결", status: "completed", assignee: "김지수", team: "공정기술팀", timestamp: "2025-01-27 16:00" },
      ],
      workPackages: [],
      messages: [
        { id: "msg-070", ticketId: "EVT-009", author: "강민우", role: "requester", messageType: "opinion", content: "FCC Riser Outlet Temp 변동폭 +/-5C 발생. 분석 요청드립니다.", timestamp: "2025-01-27T14:00:00Z" },
        { id: "msg-071", ticketId: "EVT-009", author: "김지수", role: "assignee", messageType: "opinion", content: "확인 결과 Feed Rate 변동에 의한 일시적 현상입니다. 현재 범위 내 운전으로 별도 조치 불필요합니다.", timestamp: "2025-01-27T16:00:00Z" },
        { id: "msg-072", ticketId: "EVT-009", author: "System", role: "system", messageType: "status_change", content: "이벤트가 구두 설명 후 종결 처리되었습니다. 커뮤니케이션 내용: Feed Rate 변동에 의한 일시적 현상으로 구두 설명 완료.", timestamp: "2025-01-27T16:00:00Z" },
      ],
      opinions: [],
      comments: [],
    },
    {
      id: "EVT-010",
      title: "CDU Preheat Train 열교환기 성능 점검",
      description: "CDU Preheat Train 열교환기 전반적 성능 점검. 에너지 효율 개선 기회 발굴 목적.",
      ticketType: "Improvement",
      priority: "P3",
      impact: "Energy",
      owner: "김지수",
      requester: "정태영",
      status: "Closed",
      createdDate: "2025-01-10",
      dueDate: "2025-01-30",
      closedDate: "2025-01-29",
      accessLevel: "Public",
      unit: "CDU",
      area: "Preheat",
      equipment: "Preheat Train (E-101 ~ E-110)",
      tags: ["TI-1051", "TI-1052", "UA-CDU"],
      fromTime: "2025-01-01T00:00",
      toTime: "2025-01-10T23:59",
      context: {
        unit: "CDU",
        area: "Preheat",
        equipment: "Preheat Train (E-101 ~ E-110)",
        tags: ["TI-1051", "TI-1052", "UA-CDU"],
        timeRange: "2025-01-01 ~ 01-10",
      },
      processStatus: "closed",
      processFlow: [
        { step: "issued", label: "이벤트 발행", status: "completed", assignee: "정태영", team: "에너지관리팀", timestamp: "2025-01-10 09:00" },
        { step: "accepted", label: "접수", status: "completed", assignee: "김지수", team: "공정기술팀", timestamp: "2025-01-10 10:00" },
        { step: "review", label: "기술검토", status: "completed", assignee: "김지수", team: "공정기술팀", timestamp: "2025-01-25 14:00" },
        { step: "publisher-confirm", label: "발행자 확인", status: "completed", assignee: "김지수", team: "공정기술팀", timestamp: "2025-01-28 10:00" },
        { step: "closed", label: "종결", status: "completed", timestamp: "2025-01-29 09:00" },
      ],
      executiveSummary: "CDU Preheat Train 열교환기 10기에 대한 종합 성능 점검 완료. E-103, E-107 Fouling 진행 확인되어 다음 T/A 시 Cleaning 계획 수립. 즉시 조치 불요.\n\n전반적으로 Preheat Gain은 설계 대비 92% 수준으로 양호한 편이나, 개별 열교환기의 Cleaning 주기 최적화를 통해 추가 1.5% 개선 가능할 것으로 판단됩니다.",
      workPackages: [],
      messages: [
        { id: "msg-080", ticketId: "EVT-010", author: "정태영", role: "requester", messageType: "opinion", content: "CDU Preheat Train 전반 점검 요청합니다. 에너지 개선 기회 발굴 부탁드립니다.", timestamp: "2025-01-10T09:00:00Z" },
        { id: "msg-081", ticketId: "EVT-010", author: "System", role: "system", messageType: "status_change", content: "김지수님이 이벤트를 접수하였습니다.", timestamp: "2025-01-10T10:00:00Z" },
        { id: "msg-082", ticketId: "EVT-010", author: "김지수", role: "assignee", messageType: "opinion", content: "10기 열교환기 점검 완료. E-103, E-107 Fouling 확인. 상세 Report 작성 후 종결하겠습니다.", timestamp: "2025-01-25T14:00:00Z" },
        { id: "msg-083", ticketId: "EVT-010", author: "System", role: "system", messageType: "status_change", content: "이벤트가 종결되었습니다.", timestamp: "2025-01-29T09:00:00Z" },
      ],
      opinions: [
        {
          id: "op-080", author: "김지수", team: "공정기술팀",
          templateType: "analysis-review", templateLabel: "분석 검토",
          fields: [
            { label: "분석 항목", value: "CDU Preheat Train E-101~E-110 개별 성능 점검" },
            { label: "분석 결과", value: "전체 Preheat Gain 설계 대비 92%. E-103 UA 23% 하락, E-107 UA 18% 하락 확���." },
            { label: "조치 사항", value: "다음 T/A(2025년 4월) 시 E-103, E-107 Chemical Cleaning 계획 수립" },
            { label: "효과 예상", value: "Cleaning 후 Preheat Gain 1.5%p 개선, 연료 절감 약 $50K/yr 예상" },
          ],
          status: "submitted", createdAt: "2025-01-24T14:00:00Z", submittedAt: "2025-01-25T14:00:00Z",
        },
      ],
      comments: [],
    },
    // ==================== 빠른 문의 (Quick Inquiry) ====================
    {
      id: "QI-001",
      title: "TI-2001 온도 이상 관련 문의",
      description: "어제부터 TI-2001 온도가 평소보다 5도 정도 높게 나오는데, 확인 부탁드립니다. 다른 이상징후는 없습니다.",
      ticketType: "QuickInquiry",
      priority: "P3",
      impact: "Operations",
      owner: "박영희",
      requester: "김철수",
      status: "Open",
      createdDate: "2026-03-05",
      dueDate: "",
      accessLevel: "Team",
      unit: "HCR",
      workPackages: [],
      messages: [
        { id: "qi-msg-001", ticketId: "QI-001", author: "김철수", role: "requester", messageType: "opinion", content: "어제부터 TI-2001 온도가 평소보다 5도 정도 높게 나오는데, 확인 부탁드립니다. 다른 이상징후는 없습니다.", timestamp: "2026-03-05T09:30:00Z" },
        { id: "qi-msg-002", ticketId: "QI-001", author: "박영희", role: "assignee", messageType: "response", content: "확인했습니다. Feed 조성 변화로 인한 것으로 보입니다. 현재 Heavy 성분 비율이 지난주 대비 2.3% 증가했네요.", timestamp: "2026-03-05T10:15:00Z" },
        { id: "qi-msg-003", ticketId: "QI-001", author: "김철수", role: "requester", messageType: "inquiry", content: "그렇군요. 그러면 특별히 조치할 사항은 없을까요?", timestamp: "2026-03-05T10:20:00Z" },
        { id: "qi-msg-004", ticketId: "QI-001", author: "박영희", role: "assignee", messageType: "response", content: "현재로서는 Guide 범위 내이므로 특별한 조치는 불필요합니다. 다만 410도 이상 상승 시 Quench 유량 조정을 검토해주세요. 트렌드 첨부해드립니다.", timestamp: "2026-03-05T10:30:00Z", dataBoxes: [{ id: "db-qi-001", type: "trend", config: { tags: ["TI-2001"], fromDate: "2026-03-01", toDate: "2026-03-05", title: "TI-2001 온도 트렌드" } }] },
      ],
      comments: [],
    },
    {
      id: "QI-002",
      title: "VDU P-301 펌프 진동 관련 질문",
      description: "P-301 펌프 진동이 약간 증가한 것 같은데 정상 범위인지 확인 부탁드립니다.",
      ticketType: "QuickInquiry",
      priority: "P3",
      impact: "Operations",
      owner: "이정민",
      requester: "박성호",
      status: "Open",
      createdDate: "2026-03-04",
      dueDate: "",
      accessLevel: "Team",
      unit: "VDU",
      workPackages: [],
      messages: [
        { id: "qi-msg-010", ticketId: "QI-002", author: "박성호", role: "requester", messageType: "opinion", content: "P-301 펌프 진동이 약간 증가한 것 같은데 정상 범위인지 확인 부탁드립니다.", timestamp: "2026-03-04T14:00:00Z" },
        { id: "qi-msg-011", ticketId: "QI-002", author: "이정민", role: "assignee", messageType: "response", content: "VI-301 데이터 확인 결과 2.8mm/s로 경보 기준(4.5mm/s) 이내입니다. 다만 지난달 평균 2.1mm/s 대비 상승은 확인됩니다.", timestamp: "2026-03-04T14:30:00Z" },
        { id: "qi-msg-012", ticketId: "QI-002", author: "이정민", role: "assignee", messageType: "response", content: "DCS 화면 첨부드립니다. 현재로서는 모니터링 유지하면서 3.5mm/s 초과 시 보고 부탁드립니다.", timestamp: "2026-03-04T14:32:00Z", dataBoxes: [{ id: "db-qi-002", type: "dcs", config: { graphicNumber: "VDU-P301", title: "P-301 펌프 상세" } }] },
      ],
      comments: [],
    },
  ]
}
