import type { Ticket } from "./types"

export function getMockTickets(): Ticket[] {
  return [
    // 진행 중 티켓 (30개)
    {
      id: "1",
      title: "VDU Overhead Temperature 가이드 검토",
      description: "생산팀 요청: VDU 컬럼 오버헤드 온도 가이드 재검토 필요",
      ticketType: "Trouble",
      priority: "P3",
      impact: "Throughput",
      owner: "Process Engineer A",
      requester: "Operations Manager",
      status: "Open",
      createdDate: "2024-01-28",
      dueDate: "2024-02-05",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Operations"],
      context: {
        unit: "VDU",
        area: "Distillation",
        tags: ["T-201", "Overhead"],
        timeRange: "2024-01-25 ~ 2024-01-28",
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "2",
      title: "HCR Feed 구성 최적화 검토",
      description: "HCR 공정의 Feed 구성을 최적화하여 수율 개선 방안 검토",
      ticketType: "Improvement",
      priority: "P2",
      impact: "Yield",
      owner: "Process Engineer A",
      status: "In Progress",
      createdDate: "2024-01-20",
      dueDate: "2024-03-01",
      bottleneck: "Decision pending (Process Engineering)",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Planning", "Management"],
      context: {
        unit: "HCR",
        area: "Reaction",
        tags: ["Reactor-301", "Feed"],
        timeRange: "2024-01-01 ~ 2024-01-20",
      },
      workPackages: [
        {
          id: "wp-1",
          ticketId: "2",
          wpType: "Analysis",
          title: "현재 Feed 구성 분석",
          description: "현재 Feed 구성 및 운전 데이터 분석",
          ownerTeam: "DX Team",
          status: "Done",
          dueDate: "2024-02-01",
          logs: [],
          attachments: [],
        },
        {
          id: "wp-2",
          ticketId: "2",
          wpType: "Decision",
          title: "최적화 방안 결정",
          description: "분석 결과를 바탕으로 최적 Feed 구성 결정",
          ownerTeam: "Process Engineering",
          status: "In Progress",
          dueDate: "2024-02-15",
          logs: [],
          attachments: [],
        },
        {
          id: "wp-3",
          ticketId: "2",
          wpType: "Execution",
          title: "스케줄링 반영",
          description: "최적 Feed 구성을 스케줄링에 반영",
          ownerTeam: "Planning Team",
          status: "Not Started",
          dueDate: "2024-02-25",
          logs: [],
          attachments: [],
        },
        {
          id: "wp-4",
          ticketId: "2",
          wpType: "Validation",
          title: "실행 결과 검증",
          description: "변경 후 수율 개선 효과 검증",
          ownerTeam: "DX Team",
          status: "Not Started",
          dueDate: "2024-03-01",
          logs: [],
          attachments: [],
        },
      ],
      messages: [],
    },
    {
      id: "3",
      title: "CDU Furnace 효율 개선",
      description: "CDU Furnace의 열효율 개선을 통한 에너지 절감",
      ticketType: "Improvement",
      priority: "P2",
      impact: "Energy",
      owner: "Process Engineer A",
      status: "Open",
      createdDate: "2024-01-25",
      dueDate: "2024-04-01",
      accessLevel: "Public",
      context: {
        unit: "CDU",
        area: "Heating",
        tags: ["F-101", "Furnace"],
        timeRange: "2023-12-01 ~ 2024-01-25",
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "4",
      title: "VDU 제품 품질 이상 조사",
      description: "VDU 제품 품질이 스펙 범위 하한으로 이동하는 현상 조사",
      ticketType: "Trouble",
      priority: "P1",
      impact: "Quality",
      owner: "Process Engineer A",
      status: "In Progress",
      createdDate: "2024-01-26",
      dueDate: "2024-02-10",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "QA", "Operations"],
      context: {
        unit: "VDU",
        area: "Separation",
        tags: ["Column-201", "Product"],
        timeRange: "2024-01-20 ~ 2024-01-26",
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "5",
      title: "CCR Catalyst Activity 모니터링 개선",
      description: "CCR Catalyst Activity 실시간 모니터링 시스템 개선",
      ticketType: "Improvement",
      priority: "P3",
      impact: "Operations",
      owner: "Process Engineer A",
      status: "Open",
      createdDate: "2024-01-22",
      dueDate: "2024-03-15",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "DX", "Operations"],
      context: {
        unit: "CCR",
        area: "Catalyst",
        tags: ["Reactor-401"],
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "6",
      title: "HCR Reactor 압력 이상 조사",
      description: "HCR Reactor 압력이 평소보다 높게 유지되는 현상 조사",
      ticketType: "Trouble",
      priority: "P1",
      impact: "Safety",
      owner: "Process Engineer A",
      status: "Open",
      createdDate: "2024-01-27",
      dueDate: "2024-02-03",
      accessLevel: "Public",
      context: {
        unit: "HCR",
        area: "Reaction",
        tags: ["Reactor-301", "PT-301"],
        timeRange: "2024-01-24 ~ 2024-01-27",
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "7",
      title: "CDU Energy Recovery 프로젝트",
      description: "CDU 공정 폐열 회수를 통한 에너지 효율 향상 프로젝트",
      ticketType: "Change",
      priority: "P2",
      impact: "Energy",
      owner: "Process Engineer A",
      status: "Open",
      createdDate: "2024-01-15",
      dueDate: "2024-06-01",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Project", "Management"],
      context: {
        unit: "CDU",
        area: "Heat Exchange",
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "8",
      title: "VDU Vacuum System 성능 점검",
      description: "VDU Vacuum System 성능 저하 현상 점검 및 개선",
      ticketType: "Trouble",
      priority: "P2",
      impact: "Throughput",
      owner: "Process Engineer A",
      status: "Open",
      createdDate: "2024-01-24",
      dueDate: "2024-02-20",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Maintenance", "Operations"],
      context: {
        unit: "VDU",
        area: "Vacuum",
        tags: ["Ejector-201", "PT-205"],
        timeRange: "2024-01-15 ~ 2024-01-24",
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "9",
      title: "CCR Regenerator 온도 가이드 업데이트",
      description: "CCR Regenerator 최적 온도 가이드 재검토 및 업데이트",
      ticketType: "Request",
      priority: "P3",
      impact: "Operations",
      owner: "Process Engineer A",
      status: "Open",
      createdDate: "2024-01-23",
      dueDate: "2024-02-15",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Operations"],
      context: {
        unit: "CCR",
        area: "Regeneration",
        tags: ["Regenerator-401", "TI-405"],
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "10",
      title: "HCR 제품 수율 개선 분석",
      description: "HCR 제품 수율 향상을 위한 운전 조건 최적화 분석",
      ticketType: "Analysis",
      priority: "P2",
      impact: "Yield",
      owner: "Process Engineer A",
      status: "Open",
      createdDate: "2024-01-21",
      dueDate: "2024-03-10",
      accessLevel: "Public",
      context: {
        unit: "HCR",
        area: "Reaction",
        tags: ["Reactor-301"],
        timeRange: "2023-10-01 ~ 2024-01-21",
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "11",
      title: "CDU Column Tray 청소 계획 수립",
      description: "CDU Main Column Tray 청소 시기 및 방법 검토",
      ticketType: "Request",
      priority: "P2",
      impact: "Throughput",
      owner: "Process Engineer A",
      status: "Open",
      createdDate: "2024-01-26",
      dueDate: "2024-02-28",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Maintenance", "Operations"],
      context: {
        unit: "CDU",
        area: "Distillation",
        tags: ["Column-101"],
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "12",
      title: "VDU Heat Exchanger 파울링 분석",
      description: "VDU Heat Exchanger 파울링 진행 속도 분석 및 대책 수립",
      ticketType: "Analysis",
      priority: "P2",
      impact: "Energy",
      owner: "Process Engineer A",
      status: "In Progress",
      createdDate: "2024-01-19",
      dueDate: "2024-03-01",
      accessLevel: "Public",
      context: {
        unit: "VDU",
        area: "Heat Exchange",
        tags: ["HX-201", "HX-202"],
        timeRange: "2023-11-01 ~ 2024-01-19",
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "13",
      title: "HCR Catalyst 교체 주기 재검토",
      description: "HCR Catalyst 교체 주기 최적화를 통한 비용 절감 검토",
      ticketType: "Improvement",
      priority: "P3",
      impact: "Cost",
      owner: "Process Engineer A",
      status: "Open",
      createdDate: "2024-01-17",
      dueDate: "2024-04-30",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Management"],
      context: {
        unit: "HCR",
        area: "Catalyst",
        tags: ["Reactor-301"],
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "14",
      title: "CCR Product Separator 압력 최적화",
      description: "CCR Product Separator 운전 압력 최적화를 통한 에너지 절감",
      ticketType: "Improvement",
      priority: "P3",
      impact: "Energy",
      owner: "Process Engineer A",
      status: "Open",
      createdDate: "2024-01-25",
      dueDate: "2024-03-20",
      accessLevel: "Public",
      context: {
        unit: "CCR",
        area: "Separation",
        tags: ["Separator-401"],
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "15",
      title: "CDU Pump Seal 누출 점검",
      description: "CDU Bottom Pump Seal 누출 현상 점검 및 조치",
      ticketType: "Trouble",
      priority: "P1",
      impact: "Safety",
      owner: "Process Engineer A",
      status: "In Progress",
      createdDate: "2024-01-28",
      dueDate: "2024-02-05",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Maintenance"],
      context: {
        unit: "CDU",
        area: "Pumping",
        tags: ["Pump-102"],
        timeRange: "2024-01-27 ~ 2024-01-28",
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "16",
      title: "VDU Steam System 효율 분석",
      description: "VDU Steam System 전체 효율 분석 및 개선안 도출",
      ticketType: "Analysis",
      priority: "P2",
      impact: "Energy",
      owner: "Process Engineer A",
      status: "Open",
      createdDate: "2024-01-18",
      dueDate: "2024-03-30",
      accessLevel: "Public",
      context: {
        unit: "VDU",
        area: "Utility",
        tags: ["Steam"],
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "17",
      title: "HCR Quench System 온도 제어 개선",
      description: "HCR Quench System 온도 제어 로직 개선",
      ticketType: "Change",
      priority: "P2",
      impact: "Operations",
      owner: "Process Engineer A",
      status: "Open",
      createdDate: "2024-01-24",
      dueDate: "2024-03-15",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Control", "Operations"],
      context: {
        unit: "HCR",
        area: "Quench",
        tags: ["TIC-305"],
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "18",
      title: "CCR Recycle Gas Compressor 진동 모니터링",
      description: "CCR Recycle Gas Compressor 진동 트렌드 분석 및 이상 징후 모니터링",
      ticketType: "Request",
      priority: "P2",
      impact: "Safety",
      owner: "Process Engineer A",
      status: "Open",
      createdDate: "2024-01-23",
      dueDate: "2024-02-28",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Maintenance"],
      context: {
        unit: "CCR",
        area: "Compression",
        tags: ["Compressor-401", "Vibration"],
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "19",
      title: "CDU Crude 전처리 최적화 검토",
      description: "CDU Crude 전처리 공정 최적화를 통한 처리량 증대",
      ticketType: "Improvement",
      priority: "P2",
      impact: "Throughput",
      owner: "Process Engineer A",
      status: "Open",
      createdDate: "2024-01-20",
      dueDate: "2024-04-15",
      accessLevel: "Public",
      context: {
        unit: "CDU",
        area: "Pretreatment",
        tags: ["Desalter-101"],
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "20",
      title: "VDU Side Draw 제품 품질 안정화",
      description: "VDU Side Draw 제품 품질 변동 원인 분석 및 안정화",
      ticketType: "Trouble",
      priority: "P1",
      impact: "Quality",
      owner: "Process Engineer A",
      status: "In Progress",
      createdDate: "2024-01-27",
      dueDate: "2024-02-12",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "QA", "Operations"],
      context: {
        unit: "VDU",
        area: "Side Draw",
        tags: ["Column-201", "Draw-3"],
        timeRange: "2024-01-20 ~ 2024-01-27",
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "21",
      title: "HCR Feed Heater 성능 점검",
      description: "HCR Feed Heater 성능 저하 점검 및 개선",
      ticketType: "Request",
      priority: "P2",
      impact: "Energy",
      owner: "Process Engineer A",
      status: "Open",
      createdDate: "2024-01-22",
      dueDate: "2024-03-01",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Maintenance"],
      context: {
        unit: "HCR",
        area: "Heating",
        tags: ["Heater-301"],
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "22",
      title: "CCR Platformer 운전 조건 최적화",
      description: "CCR Platformer 운전 조건 최적화를 통한 수율 및 품질 개선",
      ticketType: "Improvement",
      priority: "P2",
      impact: "Yield",
      owner: "Process Engineer A",
      status: "Open",
      createdDate: "2024-01-19",
      dueDate: "2024-04-30",
      accessLevel: "Public",
      context: {
        unit: "CCR",
        area: "Reaction",
        tags: ["Reactor-401", "Reactor-402"],
        timeRange: "2023-07-01 ~ 2024-01-19",
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "23",
      title: "CDU Overhead Condenser 청소 계획",
      description: "CDU Overhead Condenser 청소 시기 및 방법 계획 수립",
      ticketType: "Request",
      priority: "P3",
      impact: "Operations",
      owner: "Process Engineer A",
      status: "Open",
      createdDate: "2024-01-26",
      dueDate: "2024-03-15",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Maintenance", "Operations"],
      context: {
        unit: "CDU",
        area: "Overhead",
        tags: ["Condenser-101"],
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "24",
      title: "VDU Wash Water 시스템 개선",
      description: "VDU Wash Water 시스템 효율 개선 및 오염 방지",
      ticketType: "Improvement",
      priority: "P3",
      impact: "Operations",
      owner: "Process Engineer A",
      status: "Open",
      createdDate: "2024-01-21",
      dueDate: "2024-04-01",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Operations"],
      context: {
        unit: "VDU",
        area: "Overhead",
        tags: ["Wash Water"],
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "25",
      title: "HCR Hydrogen Purity 이상 조사",
      description: "HCR Hydrogen Purity 저하 원인 조사 및 대책 수립",
      ticketType: "Trouble",
      priority: "P1",
      impact: "Quality",
      owner: "Process Engineer A",
      status: "In Progress",
      createdDate: "2024-01-28",
      dueDate: "2024-02-08",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Operations"],
      context: {
        unit: "HCR",
        area: "Hydrogen",
        tags: ["Separator-302", "Purity"],
        timeRange: "2024-01-25 ~ 2024-01-28",
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "26",
      title: "CCR Catalyst Regeneration 효율 분석",
      description: "CCR Catalyst Regeneration 효율 분석 및 개선 방안 검토",
      ticketType: "Analysis",
      priority: "P2",
      impact: "Operations",
      owner: "Process Engineer A",
      status: "Open",
      createdDate: "2024-01-18",
      dueDate: "2024-03-31",
      accessLevel: "Public",
      context: {
        unit: "CCR",
        area: "Regeneration",
        tags: ["Regenerator-401"],
        timeRange: "2023-06-01 ~ 2024-01-18",
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "27",
      title: "CDU Side Stripper 운전 최적화",
      description: "CDU Side Stripper 운전 조건 최적화를 통한 제품 품질 개선",
      ticketType: "Improvement",
      priority: "P3",
      impact: "Quality",
      owner: "Process Engineer A",
      status: "Open",
      createdDate: "2024-01-24",
      dueDate: "2024-03-30",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Operations"],
      context: {
        unit: "CDU",
        area: "Side Stripper",
        tags: ["Stripper-102"],
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "28",
      title: "VDU Reboiler Fouling 대책",
      description: "VDU Reboiler Fouling 방지 대책 수립",
      ticketType: "Change",
      priority: "P2",
      impact: "Energy",
      owner: "Process Engineer A",
      status: "Open",
      createdDate: "2024-01-23",
      dueDate: "2024-04-01",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Maintenance"],
      context: {
        unit: "VDU",
        area: "Reboiler",
        tags: ["Reboiler-201"],
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "29",
      title: "HCR Effluent Cooler 청소 필요성 검토",
      description: "HCR Effluent Cooler 청소 필요성 검토 및 계획 수립",
      ticketType: "Request",
      priority: "P2",
      impact: "Operations",
      owner: "Process Engineer A",
      status: "Open",
      createdDate: "2024-01-25",
      dueDate: "2024-03-15",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Maintenance"],
      context: {
        unit: "HCR",
        area: "Cooling",
        tags: ["Cooler-302"],
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "30",
      title: "CCR Product Fractionator 압력 제어 개선",
      description: "CCR Product Fractionator 압력 제어 로직 개선",
      ticketType: "Change",
      priority: "P2",
      impact: "Operations",
      owner: "Process Engineer A",
      status: "Open",
      createdDate: "2024-01-22",
      dueDate: "2024-03-30",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Control", "Operations"],
      context: {
        unit: "CCR",
        area: "Fractionation",
        tags: ["Column-402", "PIC-405"],
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "new-1",
      title: "CDU Column 압력 이상 현상 조사",
      description: "CDU Main Column 상부 압력이 평소보다 0.3 bar 높게 유지되는 현상 발생. 원인 파악 및 대책 필요",
      ticketType: "Trouble",
      priority: "P1",
      impact: "Safety",
      owner: "김지수",
      status: "Open",
      createdDate: "2024-01-29",
      dueDate: "2024-02-05",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Operations", "Safety"],
      context: {
        unit: "CDU",
        area: "Distillation",
        tags: ["Column-101", "PT-105"],
        timeRange: "2024-01-27 ~ 2024-01-29",
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "new-2",
      title: "VDU Vacuum Pump 성능 저하 개선",
      description: "VDU Vacuum Pump의 성능이 점진적으로 저하되고 있음. 유지보수 계획 수립 필요",
      ticketType: "Request",
      priority: "P2",
      impact: "Throughput",
      owner: "김지수",
      status: "In Progress",
      createdDate: "2024-01-27",
      dueDate: "2024-02-20",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Maintenance"],
      context: {
        unit: "VDU",
        area: "Vacuum System",
        tags: ["Pump-201", "Vacuum"],
        timeRange: "2024-01-15 ~ 2024-01-27",
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "new-3",
      title: "HCR 수소 소비율 증가 원인 분석",
      description: "최근 2주간 HCR의 수소 소비율이 5% 증가. 운전 조건 변화 및 촉매 상태 분석 필요",
      ticketType: "Analysis",
      priority: "P2",
      impact: "Cost",
      owner: "김지수",
      status: "Open",
      createdDate: "2024-01-28",
      dueDate: "2024-02-25",
      accessLevel: "Public",
      context: {
        unit: "HCR",
        area: "Reaction",
        tags: ["Reactor-301", "H2 Consumption"],
        timeRange: "2024-01-10 ~ 2024-01-28",
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "new-4",
      title: "CCR 제품 Octane 수치 향상 방안",
      description: "CCR 제품 Octane 수치를 0.5 포인트 향상시킬 수 있는 운전 조건 최적화 검토",
      ticketType: "Improvement",
      priority: "P2",
      impact: "Quality",
      owner: "김지수",
      status: "Open",
      createdDate: "2024-01-26",
      dueDate: "2024-03-15",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "QA", "Operations"],
      context: {
        unit: "CCR",
        area: "Reaction",
        tags: ["Reactor-401", "Octane"],
        timeRange: "2023-12-01 ~ 2024-01-26",
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "new-5",
      title: "CDU Desalter 효율 점검",
      description: "CDU Desalter의 염분 제거 효율이 목표치보다 낮음. 운전 조건 재검토 필요",
      ticketType: "Request",
      priority: "P3",
      impact: "Operations",
      owner: "김지수",
      status: "Open",
      createdDate: "2024-01-25",
      dueDate: "2024-02-28",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Operations"],
      context: {
        unit: "CDU",
        area: "Pretreatment",
        tags: ["Desalter-101", "Brine"],
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "new-6",
      title: "VDU Heat Exchanger Network 최적화",
      description: "VDU Heat Exchanger Network의 열회수율을 개선하여 에너지 효율 향상",
      ticketType: "Improvement",
      priority: "P2",
      impact: "Energy",
      owner: "김지수",
      status: "In Progress",
      createdDate: "2024-01-22",
      dueDate: "2024-04-01",
      accessLevel: "Public",
      context: {
        unit: "VDU",
        area: "Heat Exchange",
        tags: ["HX-201", "HX-202", "HX-203"],
        timeRange: "2023-09-01 ~ 2024-01-22",
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "new-7",
      title: "HCR Compressor 진동 이상",
      description: "HCR Recycle Gas Compressor의 진동값이 경보 수준에 근접. 긴급 점검 필요",
      ticketType: "Trouble",
      priority: "P1",
      impact: "Safety",
      owner: "김지수",
      status: "In Progress",
      createdDate: "2024-01-29",
      dueDate: "2024-02-08",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Maintenance", "Safety"],
      context: {
        unit: "HCR",
        area: "Compression",
        tags: ["Compressor-301", "Vibration"],
        timeRange: "2024-01-26 ~ 2024-01-29",
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "new-8",
      title: "CCR Catalyst 순환율 변경 효과 검증",
      description: "CCR Catalyst 순환율을 변경했을 때의 제품 품질 및 수율 영향 분석",
      ticketType: "Analysis",
      priority: "P3",
      impact: "Operations",
      owner: "김지수",
      status: "Open",
      createdDate: "2024-01-24",
      dueDate: "2024-03-10",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Operations"],
      context: {
        unit: "CCR",
        area: "Catalyst Circulation",
        tags: ["Regenerator-401"],
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "new-9",
      title: "CDU Bottom Product 품질 안정화",
      description: "CDU Bottom Product의 점도가 스펙 상한에 근접하는 현상. 운전 조건 조정 필요",
      ticketType: "Trouble",
      priority: "P2",
      impact: "Quality",
      owner: "김지수",
      status: "Open",
      createdDate: "2024-01-28",
      dueDate: "2024-02-15",
      accessLevel: "Public",
      context: {
        unit: "CDU",
        area: "Bottom",
        tags: ["Column-101", "Viscosity"],
        timeRange: "2024-01-22 ~ 2024-01-28",
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "new-10",
      title: "VDU Side Cut 수율 개선 프로젝트",
      description: "VDU Side Cut 제품의 수율을 2% 향상시키기 위한 종합적인 개선 프로젝트",
      ticketType: "Change",
      priority: "P2",
      impact: "Yield",
      owner: "김지수",
      status: "Open",
      createdDate: "2024-01-20",
      dueDate: "2024-05-01",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Management", "Planning"],
      context: {
        unit: "VDU",
        area: "Side Cut",
        tags: ["Column-201", "Draw-2", "Draw-3"],
        timeRange: "2023-06-01 ~ 2024-01-20",
      },
      workPackages: [],
      messages: [],
    },

    // 모델 개선 요청 티켓
    {
      id: "model-1",
      title: "HCR RTO 모델 성능 저하 - 재구성 요청",
      description: "HCR RTO 모델의 예측 정확도가 최근 2주간 지속적으로 하락. 모델 재구성 필요",
      ticketType: "ModelImprovement",
      priority: "P2",
      impact: "Operations",
      owner: "김지수",
      requester: "김지수",
      status: "Open",
      createdDate: "2024-01-28",
      dueDate: "2024-02-20",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "DX"],
      context: {
        unit: "HCR",
        area: "RTO Model",
        tags: ["RTO-HCR", "Model Performance"],
      },
      modelRequest: {
        category: "model-rebuild",
        targetModel: "HCR RTO v3.2",
        receivingTeam: "DX Modeling팀",
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "model-2",
      title: "CCR APC 가동 요청 - 재기동 후 미연결",
      description: "CCR 공정 재기동 후 APC가 DCS와 연동되지 않는 상태. APC 재가동 요청",
      ticketType: "ModelImprovement",
      priority: "P1",
      impact: "Operations",
      owner: "김지수",
      requester: "김지수",
      status: "In Progress",
      createdDate: "2024-01-29",
      dueDate: "2024-02-05",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "DX", "Operations"],
      context: {
        unit: "CCR",
        area: "APC",
        tags: ["APC-CCR", "DCS-Link"],
      },
      modelRequest: {
        category: "apc-activation",
        targetModel: "CCR APC Controller",
        receivingTeam: "APC운영팀",
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "model-3",
      title: "VDU AI/ML 예측 모델 M2M 통신 장애",
      description: "VDU 수율 예측 AI/ML 모델과 DCS 간 M2M 통신이 끊김. 네트워크 장애 해결 필요",
      ticketType: "ModelImprovement",
      priority: "P1",
      impact: "Operations",
      owner: "김지수",
      requester: "김지수",
      status: "Open",
      createdDate: "2024-01-30",
      dueDate: "2024-02-03",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "DX", "IT"],
      context: {
        unit: "VDU",
        area: "AI/ML Model",
        tags: ["ML-VDU-Yield", "M2M"],
      },
      modelRequest: {
        category: "m2m-network",
        targetModel: "VDU Yield Predictor v2.1",
        receivingTeam: "IT인프라팀",
      },
      workPackages: [],
      messages: [],
    },

    // 실공정 테스트 티켓
    {
      id: "test-1",
      title: "HCR Quench 분배 비율 변경 테스트",
      description: "HCR 1st/2nd Bed 간 Quench 분배 비율 변경이 Reactor 온도 프로파일 개선에 미치는 영향 검증",
      ticketType: "ProcessTest",
      priority: "P2",
      impact: "Throughput",
      owner: "김지수",
      requester: "김지수",
      status: "In Progress",
      createdDate: "2024-01-20",
      dueDate: "2024-02-28",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Operations"],
      context: {
        unit: "HCR",
        area: "Quench System",
        tags: ["Quench-301", "TI-305", "TI-310"],
        timeRange: "2024-01-25 ~ 2024-02-10",
      },
      processTest: {
        hypothesis: "1st Bed Quench 비율을 현행 45%에서 40%로 줄이면 2nd Bed 입구 온도가 3~5도 낮아져 촉매 수명 연장 기대",
        testStartDate: "2024-01-25",
        testEndDate: "2024-02-10",
        targetVariables: ["Quench-301 Flow Ratio", "TI-305 (1st Bed Out)", "TI-310 (2nd Bed In)", "WABT"],
        operatingGuide: "1st Bed Quench Valve 45% → 40% 조정, 2nd Bed Quench Valve 보정. Reactor dT 모니터링 강화",
        feedbackDeadline: "2024-03-12",
        testStatus: "in-progress",
        reviewedByProduction: true,
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "test-2",
      title: "CDU Desalter Wash Water 비율 최적화 테스트",
      description: "Desalter Wash Water 비율을 5%에서 4%로 낮춰 에너지 절감 가능성 검증",
      ticketType: "ProcessTest",
      priority: "P3",
      impact: "Energy",
      owner: "김지수",
      requester: "김지수",
      status: "Open",
      createdDate: "2024-01-28",
      dueDate: "2024-03-15",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Operations"],
      context: {
        unit: "CDU",
        area: "Desalter",
        tags: ["Desalter-101", "Wash-Water", "Salt-Content"],
      },
      processTest: {
        hypothesis: "Wash Water 비율 5%→4% 감소 시 염분 제거 효율 95% 이상 유지하면서 용수 및 에너지 절감 가능",
        testStartDate: "2024-02-05",
        testEndDate: "2024-02-20",
        targetVariables: ["Wash Water Flow", "Desalter Outlet Salt", "Crude Conductivity"],
        operatingGuide: "Wash Water 유량 단계적 감소 (5% → 4.5% → 4%), 매 단계 24시간 유지 후 Salt 측정",
        feedbackDeadline: "2024-03-22",
        testStatus: "planned",
        reviewedByProduction: false,
      },
      workPackages: [],
      messages: [],
    },
    {
      id: "test-3",
      title: "CCR Reactor Inlet Temp 상향 테스트",
      description: "CCR Reactor Inlet 온도 2도 상향 시 Reformate Octane 변화 검증",
      ticketType: "ProcessTest",
      priority: "P2",
      impact: "Quality",
      owner: "김지수",
      requester: "김지수",
      status: "Open",
      createdDate: "2024-01-27",
      dueDate: "2024-03-01",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Operations", "QA"],
      context: {
        unit: "CCR",
        area: "Reaction",
        tags: ["Reactor-401", "TI-401", "Octane"],
        timeRange: "2024-02-01 ~ 2024-02-15",
      },
      processTest: {
        hypothesis: "Reactor Inlet 온도 520°C→522°C 상향 시 Reformate RON 0.3~0.5 향상, Catalyst Coke 영향 미미할 것으로 예상",
        testStartDate: "2024-02-01",
        testEndDate: "2024-02-15",
        targetVariables: ["TI-401 (Reactor Inlet)", "Reformate RON", "Catalyst Coke %", "C5+ Yield"],
        operatingGuide: "Reactor Inlet 온도 0.5도 단위 단계적 상향. RON 및 Yield 매일 측정",
        feedbackDeadline: "2024-03-17",
        testStatus: "planned",
        reviewedByProduction: false,
      },
      workPackages: [],
      messages: [],
    },

    // 완료된 티켓 (20개)
    {
      id: "c1",
      title: "CDU Feed Preheat 온도 조정",
      description: "CDU Feed Preheat 온도 최적화로 에너지 효율 개선",
      ticketType: "Improvement",
      priority: "P2",
      impact: "Energy",
      owner: "Process Engineer A",
      status: "Closed",
      createdDate: "2023-12-10",
      dueDate: "2024-01-10",
      closedDate: "2024-01-09",
      accessLevel: "Public",
      context: {
        unit: "CDU",
        area: "Heating",
        tags: ["Preheater-101"],
      },
      workPackages: [],
      executiveSummary: "Feed Preheat 온도를 5도 상향 조정하여 Furnace 부하 3% 감소 달성. 연간 약 500TOE 절감 예상.",
      messages: [],
    },
    {
      id: "c2",
      title: "VDU Stripping Steam 유량 최적화",
      description: "VDU Stripping Steam 유량 최적화를 통한 제품 품질 개선",
      ticketType: "Improvement",
      priority: "P3",
      impact: "Quality",
      owner: "Process Engineer A",
      status: "Closed",
      createdDate: "2023-12-15",
      dueDate: "2024-01-20",
      closedDate: "2024-01-18",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Operations"],
      context: {
        unit: "VDU",
        area: "Stripping",
        tags: ["Column-201"],
      },
      workPackages: [],
      executiveSummary:
        "Stripping Steam 유량을 10% 감소시켜도 제품 품질 유지 가능 확인. Steam 절감 및 품질 안정화 달성.",
      messages: [],
    },
    {
      id: "c3",
      title: "HCR 촉매 재생 주기 검토",
      description: "HCR 촉매 재생 주기 최적화를 통한 운전 효율 향상",
      ticketType: "Analysis",
      priority: "P2",
      impact: "Operations",
      owner: "Process Engineer A",
      status: "Closed",
      createdDate: "2023-11-20",
      dueDate: "2023-12-31",
      closedDate: "2023-12-28",
      accessLevel: "Public",
      context: {
        unit: "HCR",
        area: "Catalyst",
        tags: ["Reactor-301"],
      },
      workPackages: [],
      executiveSummary:
        "촉매 활성도 데이터 분석 결과 재생 주기를 기존 60일에서 75일로 연장 가능. 재생 비용 연간 20% 절감.",
      messages: [],
    },
    {
      id: "c4",
      title: "CCR Compressor 진동 이상 해결",
      description: "CCR Recycle Compressor 진동 이상 원인 파악 및 해결",
      ticketType: "Trouble",
      priority: "P1",
      impact: "Safety",
      owner: "Process Engineer A",
      status: "Closed",
      createdDate: "2024-01-05",
      dueDate: "2024-01-15",
      closedDate: "2024-01-14",
      accessLevel: "Public",
      context: {
        unit: "CCR",
        area: "Compression",
        tags: ["Compressor-401"],
        timeRange: "2024-01-03 ~ 2024-01-05",
      },
      workPackages: [],
      executiveSummary:
        "진동 원인은 Suction Filter 차압 증가로 판명. Filter 교체 후 진동 정상 수준으로 복귀. 예방 점검 주기 단축 권고.",
      messages: [],
    },
    {
      id: "c5",
      title: "VDU Reflux 유량 최적화",
      description: "VDU Column Reflux 유량 최적화를 통한 에너지 절감",
      ticketType: "Improvement",
      priority: "P3",
      impact: "Energy",
      owner: "Process Engineer A",
      status: "Closed",
      createdDate: "2023-12-01",
      dueDate: "2024-01-05",
      closedDate: "2024-01-04",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Operations"],
      context: {
        unit: "VDU",
        area: "Distillation",
        tags: ["Column-201", "Reflux"],
      },
      workPackages: [],
      executiveSummary:
        "Reflux 유량을 8% 감소시켜 Reflux Pump 전력 소비 절감 및 Overhead Condenser 부하 감소. 품질 영향 없음 확인.",
      messages: [],
    },
    {
      id: "c6",
      title: "CDU Bottom Product 품질 안정화",
      description: "CDU Bottom Product 품질 변동 원인 파악 및 안정화",
      ticketType: "Trouble",
      priority: "P1",
      impact: "Quality",
      owner: "Process Engineer A",
      status: "Closed",
      createdDate: "2023-12-18",
      dueDate: "2024-01-15",
      closedDate: "2024-01-12",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "QA"],
      context: {
        unit: "CDU",
        area: "Bottom",
        tags: ["Column-101"],
      },
      workPackages: [],
      executiveSummary:
        "Bottom Draw 온도 제어 불안정이 원인. 온도 제어 PID 튜닝 후 품질 안정화 달성. 재발 방지 위해 정기 점검 추가.",
      messages: [],
    },
    {
      id: "c7",
      title: "HCR Separator 레벨 제어 개선",
      description: "HCR HP Separator 레벨 제어 로직 개선",
      ticketType: "Change",
      priority: "P2",
      impact: "Operations",
      owner: "Process Engineer A",
      status: "Closed",
      createdDate: "2023-12-05",
      dueDate: "2024-01-20",
      closedDate: "2024-01-18",
      accessLevel: "Public",
      context: {
        unit: "HCR",
        area: "Separation",
        tags: ["Separator-301", "LIC-303"],
      },
      workPackages: [],
      executiveSummary: "레벨 제어 안정화를 위해 PID 파라미터 재조정 및 밸브 응답 시간 개선. 제어 성능 향상 확인.",
      messages: [],
    },
    {
      id: "c8",
      title: "CCR Feed Pump 교체",
      description: "CCR Feed Pump 노후화로 인한 교체 작업",
      ticketType: "Request",
      priority: "P1",
      impact: "Safety",
      owner: "Process Engineer A",
      status: "Closed",
      createdDate: "2023-12-20",
      dueDate: "2024-01-10",
      closedDate: "2024-01-08",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Maintenance"],
      context: {
        unit: "CCR",
        area: "Pumping",
        tags: ["Pump-401"],
      },
      workPackages: [],
      executiveSummary: "신규 Pump 설치 완료. 진동 및 소음 감소, 효율 향상 확인. 예비품 재고 확보 권고.",
      messages: [],
    },
    {
      id: "c9",
      title: "VDU Column 차압 증가 원인 조사",
      description: "VDU Main Column 차압 증가 원인 조사 및 해결",
      ticketType: "Trouble",
      priority: "P1",
      impact: "Throughput",
      owner: "Process Engineer A",
      status: "Closed",
      createdDate: "2023-12-22",
      dueDate: "2024-01-15",
      closedDate: "2024-01-14",
      accessLevel: "Public",
      context: {
        unit: "VDU",
        area: "Distillation",
        tags: ["Column-201", "dP"],
        timeRange: "2023-12-15 ~ 2023-12-22",
      },
      workPackages: [],
      executiveSummary:
        "차압 증가 원인은 Column 내 Fouling. Wash Oil 주입 증가로 Fouling 제거 후 차압 정상화. 정기 세정 계획 수립.",
      messages: [],
    },
    {
      id: "c10",
      title: "CDU Furnace Tube 청소",
      description: "CDU Furnace Tube 청소를 통한 열효율 회복",
      ticketType: "Request",
      priority: "P2",
      impact: "Energy",
      owner: "Process Engineer A",
      status: "Closed",
      createdDate: "2023-11-15",
      dueDate: "2024-01-31",
      closedDate: "2023-12-29",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Maintenance"],
      context: {
        unit: "CDU",
        area: "Heating",
        tags: ["Furnace-101"],
      },
      workPackages: [],
      executiveSummary:
        "Furnace Tube 청소 완료 후 열효율 5% 향상. Fuel Gas 소비량 감소 확인. 연간 청소 계획 수립 권고.",
      messages: [],
    },
    {
      id: "c11",
      title: "HCR Reactor Inlet 온도 최적화",
      description: "HCR Reactor Inlet 온도 최적화를 통한 수율 개선",
      ticketType: "Improvement",
      priority: "P2",
      impact: "Yield",
      owner: "Process Engineer A",
      status: "Closed",
      createdDate: "2023-12-08",
      dueDate: "2024-01-25",
      closedDate: "2024-01-22",
      accessLevel: "Public",
      context: {
        unit: "HCR",
        area: "Reaction",
        tags: ["Reactor-301", "TI-301"],
      },
      workPackages: [],
      executiveSummary: "Inlet 온도 3도 상승으로 전환율 1.5% 향상. 제품 수율 개선 및 에너지 효율 증가 달성.",
      messages: [],
    },
    {
      id: "c12",
      title: "CCR Product Cooler 성능 개선",
      description: "CCR Product Cooler 성능 개선을 통한 냉각 효율 향상",
      ticketType: "Improvement",
      priority: "P3",
      impact: "Energy",
      owner: "Process Engineer A",
      status: "Closed",
      createdDate: "2023-12-12",
      dueDate: "2024-01-30",
      closedDate: "2024-01-26",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Maintenance"],
      context: {
        unit: "CCR",
        area: "Cooling",
        tags: ["Cooler-403"],
      },
      workPackages: [],
      executiveSummary: "Cooling Water 유량 증가 및 청소로 냉각 효율 10% 향상. 냉각수 온도 안정화 달성.",
      messages: [],
    },
    {
      id: "c13",
      title: "VDU Overhead Accumulator 레벨 이상",
      description: "VDU Overhead Accumulator 레벨 이상 원인 조사 및 해결",
      ticketType: "Trouble",
      priority: "P1",
      impact: "Operations",
      owner: "Process Engineer A",
      status: "Closed",
      createdDate: "2024-01-08",
      dueDate: "2024-01-20",
      closedDate: "2024-01-17",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Operations"],
      context: {
        unit: "VDU",
        area: "Overhead",
        tags: ["Accumulator-201", "LIC-205"],
        timeRange: "2024-01-05 ~ 2024-01-08",
      },
      workPackages: [],
      executiveSummary: "레벨 이상 원인은 제어 밸브 Sticking. 밸브 교체 후 레벨 제어 정상화. 예방 정비 추가.",
      messages: [],
    },
    {
      id: "c14",
      title: "CDU Heat Integration 개선",
      description: "CDU Heat Integration 개선을 통한 에너지 효율 향상",
      ticketType: "Change",
      priority: "P2",
      impact: "Energy",
      owner: "Process Engineer A",
      status: "Closed",
      createdDate: "2023-11-25",
      dueDate: "2024-01-15",
      closedDate: "2024-01-11",
      accessLevel: "Public",
      context: {
        unit: "CDU",
        area: "Heat Exchange",
      },
      workPackages: [],
      executiveSummary: "Heat Exchanger Network 재구성으로 Furnace 부하 4% 감소. 연간 약 600TOE 에너지 절감 예상.",
      messages: [],
    },
    {
      id: "c15",
      title: "HCR Makeup Gas 유량 최적화",
      description: "HCR Makeup Gas 유량 최적화를 통한 수소 소비 절감",
      ticketType: "Improvement",
      priority: "P3",
      impact: "Cost",
      owner: "Process Engineer A",
      status: "Closed",
      createdDate: "2023-12-18",
      dueDate: "2024-01-28",
      closedDate: "2024-01-25",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Operations"],
      context: {
        unit: "HCR",
        area: "Hydrogen",
        tags: ["FIC-304"],
      },
      workPackages: [],
      executiveSummary: "Makeup Gas 유량 7% 감소로 수소 소비량 절감. 제품 품질 유지 확인. 연간 비용 절감 효과 발생.",
      messages: [],
    },
    {
      id: "c16",
      title: "CCR Reactor 온도 프로파일 최적화",
      description: "CCR Reactor 온도 프로파일 최적화를 통한 촉매 활성 향상",
      ticketType: "Improvement",
      priority: "P2",
      impact: "Yield",
      owner: "Process Engineer A",
      status: "Closed",
      createdDate: "2023-12-10",
      dueDate: "2024-01-22",
      closedDate: "2024-01-20",
      accessLevel: "Public",
      context: {
        unit: "CCR",
        area: "Reaction",
        tags: ["Reactor-401"],
      },
      workPackages: [],
      executiveSummary: "Reactor Inlet 온도 상향 조정으로 전환율 증가. 제품 Octane 0.3 향상. 촉매 활성 개선 확인.",
      messages: [],
    },
    {
      id: "c17",
      title: "VDU Wash Oil 유량 조정",
      description: "VDU Wash Oil 유량 조정을 통한 Column 세정 효율 개선",
      ticketType: "Request",
      priority: "P3",
      impact: "Operations",
      owner: "Process Engineer A",
      status: "Closed",
      createdDate: "2024-01-02",
      dueDate: "2024-01-20",
      closedDate: "2024-01-18",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Operations"],
      context: {
        unit: "VDU",
        area: "Distillation",
        tags: ["Column-201", "Wash Oil"],
      },
      workPackages: [],
      executiveSummary: "Wash Oil 유량 15% 증가로 Column 차압 안정화. Fouling 진행 속도 감소 확인.",
      messages: [],
    },
    {
      id: "c18",
      title: "CDU Overhead System 압력 제어 개선",
      description: "CDU Overhead System 압력 제어 로직 개선",
      ticketType: "Change",
      priority: "P2",
      impact: "Operations",
      owner: "Process Engineer A",
      status: "Closed",
      createdDate: "2023-12-15",
      dueDate: "2024-01-25",
      closedDate: "2024-01-23",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "Control"],
      context: {
        unit: "CDU",
        area: "Overhead",
        tags: ["PIC-103"],
      },
      workPackages: [],
      executiveSummary: "압력 제어 로직 개선으로 압력 변동 감소. Column 운전 안정성 향상. Flare Gas 발생량 감소.",
      messages: [],
    },
    {
      id: "c19",
      title: "HCR Effluent Separator 성능 점검",
      description: "HCR Effluent Separator 성능 점검 및 개선",
      ticketType: "Request",
      priority: "P2",
      impact: "Operations",
      owner: "Process Engineer A",
      status: "Closed",
      createdDate: "2023-12-20",
      dueDate: "2024-01-30",
      closedDate: "2024-01-27",
      accessLevel: "Public",
      context: {
        unit: "HCR",
        area: "Separation",
        tags: ["Separator-302"],
      },
      workPackages: [],
      executiveSummary: "Separator 내부 점검 결과 Demister 손상 발견. 교체 후 분리 효율 개선 확인.",
      messages: [],
    },
    {
      id: "c20",
      title: "CCR Catalyst Hopper 레벨 모니터링 개선",
      description: "CCR Catalyst Hopper 레벨 모니터링 시스템 개선",
      ticketType: "Improvement",
      priority: "P3",
      impact: "Operations",
      owner: "Process Engineer A",
      status: "Closed",
      createdDate: "2024-01-05",
      dueDate: "2024-01-25",
      closedDate: "2024-01-24",
      accessLevel: "Team",
      allowedTeams: ["Engineering", "DX"],
      context: {
        unit: "CCR",
        area: "Catalyst",
        tags: ["Hopper-401"],
      },
      workPackages: [],
      executiveSummary: "레벨 센서 추가 설치 및 알람 로직 개선. 촉매 공급 안정성 향상. 실시간 모니터링 가능.",
      messages: [],
    },
  ]
}
